"""create order tables

Revision ID: 6a0864d6d008
Revises: d82d7938418d
Create Date: 2026-09-27 11:48:15.608881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0864d6d008'
down_revision: Union[str, Sequence[str], None] = 'd82d7938418d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'canceled', name='order_status_enum'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_price >= 0', name='total_price_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_user_id_created_at', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('movie_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.CheckConstraint('unit_price >= 0', name='unit_price_non_negative'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'movie_id', name='uq_order_items_order_id_movie_id')
    )
    op.create_index('ix_order_items_movie_id', 'order_items', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_movie_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_user_id_created_at', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
