"""create movies tables

Revision ID: ee9e20d05ec1
Revises: 6403751b866e
Create Date: 2026-09-23 17:48:34.301066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ee9e20d05ec1'
down_revision: Union[str, Sequence[str], None] = '6403751b866e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actors_name_lower', 'actors', [sa.literal_column('lower(name)')], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'uq_countries_code_lower',
        'countries',
        [sa.literal_column('lower(code)')],
        unique=True,
    )
    op.create_table('genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_genres_name_lower', 'genres', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('languages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_languages_name_lower', 'languages', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('movies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Released', 'Post Production', 'In Production', name='movie_status_enum'), nullable=False),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('budget >= 0', name='budget_non_negative'),
    sa.CheckConstraint('revenue >= 0', name='revenue_non_negative'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='score_range'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_movies_name_lower_date', 'movies', [sa.literal_column('lower(name)'), 'date'], unique=True)
    op.create_table('movies_actors',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
    )
    op.create_table('movies_genres',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('movies_languages',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'language_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_languages')
    op.drop_table('movies_genres')
    op.drop_table('movies_actors')
    op.drop_index('uq_movies_name_lower_date', table_name='movies')
    op.drop_table('movies')
    postgresql.ENUM(name='movie_status_enum').drop(
        op.get_bind(),
        checkfirst=True,
    )
    op.drop_index('uq_languages_name_lower', table_name='languages')
    op.drop_table('languages')
    op.drop_index('uq_genres_name_lower', table_name='genres')
    op.drop_table('genres')
    op.drop_index('uq_countries_code_lower', table_name='countries')
    op.drop_table('countries')
    op.drop_index('ix_actors_name_lower', table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
